### ISSUE TITLE
Escaping pipe symbol

### ISSUE THREAD

**Issue by birgitpolkner** [citrix/storefront-sdk#3]
I can't create Pull requests for this project... Pipe symbol is read a beginning of new table cell:

Each URL is separated by a pipe (

The only info I could find was that it probably needs to be entered as: & # 1 2 4 ; (entered with spaces, so that it renders in this box)
The article was a little inconclusive about if this works.

**Comment by ajitchelat** [comment]
@birgitpolkner I didn't quite understand what the issue is. Could you elaborate? On which file are you seeing this issue?

**Comment by birgitpolkner** [comment]
If you look at the sentence in the compiled help it ends with the opening bracket. The remaineder of the sentence does not show. In the code I see that there is a pipe symbol at that point.

**Comment by birgitpolkner** [comment]
https://github.com/citrix/storefront-sdk/blob/master/docs/using-configuration-elements.md

**Comment by ajitchelat** [comment]
Good catch! Fixed and re-compiled.
